/* ============================================================
   NATIVE MANIFEST — Setup Chrome Native Messaging host manifest
   Called by: nav setup-native-host --extension-id=<id>
   ============================================================ */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir, platform } from 'node:os';
import { execSync } from 'node:child_process';

const HOST_NAME = 'com.neuronav.daemon';

interface SetupOptions {
  extensionId?: string;
}

function getNativeHostPath(): string {
  // Find the compiled native-host.js
  const __dirname = dirname(fileURLToPath(import.meta.url));

  // In monorepo dev: same dist directory
  const localPath = resolve(__dirname, 'native-host.js');
  if (existsSync(localPath)) return localPath;

  // Global install
  try {
    const globalBin = execSync('which nav', { encoding: 'utf-8' }).trim();
    const globalDir = dirname(globalBin);
    const candidate = resolve(globalDir, '../lib/node_modules/@neuro-nav/cli/dist/native-host.js');
    if (existsSync(candidate)) return candidate;
  } catch { /* not globally installed */ }

  return localPath; // fallback
}

function getManifestDir(): string {
  const os = platform();

  if (os === 'linux') {
    // Check for Chromium-based browsers
    const chromeDir = resolve(homedir(), '.config/google-chrome/NativeMessagingHosts');
    const chromiumDir = resolve(homedir(), '.config/chromium/NativeMessagingHosts');

    // Prefer Chrome, fallback to Chromium
    if (existsSync(resolve(homedir(), '.config/google-chrome'))) return chromeDir;
    if (existsSync(resolve(homedir(), '.config/chromium'))) return chromiumDir;
    return chromeDir; // default
  }

  if (os === 'darwin') {
    return resolve(homedir(), 'Library/Application Support/Google/Chrome/NativeMessagingHosts');
  }

  if (os === 'win32') {
    // Windows uses registry, but we can still place the manifest
    return resolve(homedir(), 'AppData/Local/Google/Chrome/User Data/NativeMessagingHosts');
  }

  throw new Error(`Unsupported platform: ${os}`);
}

export function setupNativeHost(opts: SetupOptions): { success: boolean; manifestPath: string; error?: string } {
  const extensionId = opts.extensionId;

  if (!extensionId) {
    return {
      success: false,
      manifestPath: '',
      error: 'Extension ID is required. Find it at chrome://extensions (look for the ID under Neuro-Nav).',
    };
  }

  const nativeHostPath = getNativeHostPath();
  const manifestDir = getManifestDir();
  const manifestPath = resolve(manifestDir, `${HOST_NAME}.json`);

  // Create a wrapper shell script that invokes node with the native-host.js
  const wrapperDir = manifestDir;
  const wrapperPath = resolve(wrapperDir, 'neuro-nav-native-host.sh');

  const manifest = {
    name: HOST_NAME,
    description: 'Neuro-Nav — Auto-start daemon from Chrome extension',
    path: wrapperPath,
    type: 'stdio' as const,
    allowed_origins: [`chrome-extension://${extensionId}/`],
  };

  try {
    // Ensure directories exist
    if (!existsSync(manifestDir)) {
      mkdirSync(manifestDir, { recursive: true });
    }

    // Write the wrapper script (handles finding node)
    const wrapperContent = `#!/bin/bash
# Neuro-Nav Native Messaging Host wrapper
# Auto-generated by: nav setup-native-host
exec node "${nativeHostPath}" "$@"
`;
    writeFileSync(wrapperPath, wrapperContent, { mode: 0o755 });

    // Write the manifest
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

    return { success: true, manifestPath };
  } catch (err) {
    return {
      success: false,
      manifestPath,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
